#!/usr/bin/env python3
"""Generate viewer/cards.js (all English cards) for the static viewer.

Run from the repo root:
    python3 scripts/generate-viewer-data.py
"""

import glob
import json
import re

SET_ORDER = [
    "A1", "A1a", "A2", "A2a", "A2b", "A3", "A3a", "A3b",
    "A4", "A4a", "A4b",
    "B1", "B1a", "B2", "B2a", "B2b", "B3", "B3a", "B3b", "B4",
    "P-A", "P-B",
]


def set_code_from_id(card_id):
    base = card_id.rsplit("-", 1)[0]
    if base.startswith("p-"):
        return base.upper()
    return base[0].upper() + base[1:]


def main():
    cards = []
    for path in sorted(glob.glob("cards/en/*.json")):
        for card in json.load(open(path, encoding="utf-8")):
            card = dict(card)
            card["setCode"] = set_code_from_id(card["id"])
            if card.get("set"):
                card["set"] = re.sub(r"\s+", " ", card["set"]).strip()
            cards.append(card)

    order = {code: i for i, code in enumerate(SET_ORDER)}

    def sort_key(card):
        code = card["setCode"]
        return (order.get(code, len(order)), card["id"])

    cards.sort(key=sort_key)

    with open("viewer/cards.js", "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by scripts/generate-viewer-data.py. Do not edit.\n")
        fh.write("window.POKEMON_CARDS = ")
        json.dump(cards, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")

    print(f"Wrote {len(cards)} cards to viewer/cards.js")


if __name__ == "__main__":
    main()
